# Generated by Django 4.0.1 on 2022-01-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Change_Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='default-logo.jpg', null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Website Logo',
                'verbose_name_plural': 'Change Site Logo',
            },
        ),
    ]
