# Generated by Django 4.0.1 on 2022-01-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_logo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change_logo',
            name='logo',
            field=models.ImageField(blank=True, default='default-logo.png', null=True, upload_to=''),
        ),
    ]
