# Generated by Django 4.0.1 on 2022-01-24 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabrication_products', '0003_alter_fabpro_product_image_1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FabPro',
            new_name='Fabrication_Products',
        ),
    ]
