# Generated by Django 4.0.1 on 2022-01-25 00:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabrication_products', '0004_rename_fabpro_fabrication_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabrication_products',
            options={'verbose_name': 'Fabrication Product item', 'verbose_name_plural': 'Fabrication Products'},
        ),
        migrations.AlterField(
            model_name='fabrication_products',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
