# Generated by Django 4.0.1 on 2022-01-25 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabrication_products', '0005_alter_fabrication_products_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fabrication_Products',
            new_name='Fabrication_Product',
        ),
    ]
