# Generated by Django 4.0.1 on 2022-01-25 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabrication_products', '0006_rename_fabrication_products_fabrication_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fab_Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Fabrication Sub-Category',
                'verbose_name_plural': 'Fabrication Subcategories',
            },
        ),
        migrations.AddField(
            model_name='fabrication_product',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fabrication_products.fab_cat'),
        ),
    ]
