# Generated by Django 4.0.1 on 2022-01-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrication_products', '0007_fab_cat_fabrication_product_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabrication_product',
            name='product_image_1',
            field=models.ImageField(blank=True, default='product-placeholder.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='fabrication_product',
            name='thumbnail_image',
            field=models.ImageField(blank=True, default='product-placeholder.jpg', null=True, upload_to=''),
        ),
    ]
