# Generated by Django 4.0.1 on 2022-01-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('thumbnail_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
            ],
        ),
    ]
