# Generated by Django 4.0.1 on 2022-01-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='thumbnail_image',
            field=models.ImageField(blank=True, default='default_member.jpg', null=True, upload_to=''),
        ),
    ]
