# Generated by Django 4.0.1 on 2022-01-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_member_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='thumbnail_image',
            field=models.ImageField(blank=True, default='team-1.jpg', null=True, upload_to=''),
        ),
    ]
