# Generated by Django 4.0.1 on 2022-01-25 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_member_thumbnail_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name_plural': 'Team Members'},
        ),
    ]
