# Generated by Django 4.0.1 on 2022-01-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_products', '0002_cnc_cat_cnc_product_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnc_product',
            name='product_image_1',
            field=models.ImageField(blank=True, default='product-placeholder.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cnc_product',
            name='thumbnail_image',
            field=models.ImageField(blank=True, default='product-placeholder.jpg', null=True, upload_to=''),
        ),
    ]
