# Generated by Django 4.0.1 on 2022-01-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CncGal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_6', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_7', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_8', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_9', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_10', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_11', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_12', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_13', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_14', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_15', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'CNC Gallery',
            },
        ),
    ]
