# Generated by Django 4.0.1 on 2022-01-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncgallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cncgal',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='cncgal',
            name='image_10',
        ),
        migrations.RemoveField(
            model_name='cncgal',
            name='image_11',
        ),
        migrations.RemoveField(
            model_name='cncgal',
            name='image_12',
        ),
        migrations.RemoveField(
            model_name='cncgal',
            name='image_13',
        ),
        migrations.RemoveField(
            model_name='cncgal',
            name='image_14',
        ),
        migrations.RemoveField(
            model_name='cncgal',
            name='image_15',
        ),
        migrations.RemoveField(
            model_name='cncgal',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='cncgal',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='cncgal',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='cncgal',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='cncgal',
            name='image_6',
        ),
        migrations.RemoveField(
            model_name='cncgal',
            name='image_7',
        ),
        migrations.RemoveField(
            model_name='cncgal',
            name='image_8',
        ),
        migrations.RemoveField(
            model_name='cncgal',
            name='image_9',
        ),
        migrations.AddField(
            model_name='cncgal',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cncgal',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='cncgal',
            name='img_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
