# Generated by Django 4.0.1 on 2022-01-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncgallery', '0002_remove_cncgal_image_1_remove_cncgal_image_10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cncgal',
            name='img_title',
        ),
        migrations.AddField(
            model_name='cncgal',
            name='title',
            field=models.CharField(default='randomimage', max_length=200),
        ),
        migrations.AlterField(
            model_name='cncgal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
