# Generated by Django 4.0.1 on 2022-01-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cncgallery', '0004_alter_cncgal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cncgal',
            name='title',
            field=models.CharField(default='CNC Machined Example', max_length=200),
        ),
    ]
