# Generated by Django 4.0.1 on 2022-01-25 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cncgallery', '0005_alter_cncgal_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cncgal',
            options={'verbose_name': 'CNC Gallery item', 'verbose_name_plural': 'Edit CNC Gallery'},
        ),
    ]
