# Generated by Django 4.0.1 on 2022-01-26 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plastic_products', '0002_plast_cat_plastic_product_sub_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plast_cat',
            options={'verbose_name': 'Plastic Sub-Category', 'verbose_name_plural': 'PLastic Subcategories'},
        ),
    ]
