# Generated by Django 4.0.1 on 2022-01-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plastic_products', '0004_alter_plast_cat_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plastic_product',
            name='product_image_1',
            field=models.ImageField(blank=True, default='product-placeholder.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='plastic_product',
            name='thumbnail_image',
            field=models.ImageField(blank=True, default='product-placeholder.jpg', null=True, upload_to=''),
        ),
    ]
