# Generated by Django 4.0.1 on 2022-01-27 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Available social media links- view only',
                'verbose_name_plural': 'Available social media links - view only',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=2048)),
                ('media_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social_links.socialcat')),
            ],
            options={
                'verbose_name': 'Add your social media links here',
                'verbose_name_plural': 'Add your social media links here',
            },
        ),
    ]
