# Generated by Django 4.0.1 on 2022-01-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlastGal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Plastic Product Example', max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Plastic Gallery',
            },
        ),
    ]
