# Generated by Django 4.0.1 on 2022-01-25 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plastic_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plastgal',
            options={'verbose_name': 'Plastic Gallery item', 'verbose_name_plural': 'Plastic Gallery'},
        ),
    ]
