# Generated by Django 4.0.1 on 2022-01-25 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabrication_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabgal',
            options={'verbose_name': 'Fabrication Gallery item', 'verbose_name_plural': 'Edit Fabrication Gallery'},
        ),
    ]
